// Mikroraportoinnin valmiit otsikot (2.10.2026, käyttäjän taulukko "Raporttien
// jeesustaulukko.ods").
//
// Kaksi luetteloa:
//   PAIKKARYHMAT — missä raportin kohde on (ryhmä → kohta tai tila)
//   AIHEET       — mitä havaittiin tai tehtiin (aihe → alue → [luokka, otsikko])
//
// Taulukon "Havainto (Positiivinen)" ja "Havainto (Negatiivinen)" ovat tässä pelkkä
// 'havainto': sävy on jo otsikon tekstissä ("ohjeistuksen mukainen" / "puutteita
// havaittu"), eikä kolmen valinnan rinnalle kannata tuoda neljättä ja viidettä vain
// kuuden rivin takia.
//
// Tallennettuun raporttiin kirjataan TEKSTIT eikä indeksejä: kun luetteloa myöhemmin
// muokataan, vanhat raportit kertovat yhä mitä niissä valittiin.
export type Luokka = 'havainto' | 'poikkeama' | 'toimenpide';

export const PAIKKARYHMAT: { ryhma: string; paikat: string[] }[] = [
  { ryhma: 'Ulkualueet ja kehäsuojaus', paikat: [
    'Kohteen piha',
    'Viheralue',
    'Pysäköintialue',
    'Parkkihalli',
    'Autokatos',
    'Lastauslaituri',
    'Lastaustasku',
    'Ramppi',
    'Alueaita',
    'Portti',
    'Puomi',
    'Ajoeste',
    'Jätekatos',
    'Jätehuone',
    'Jätepuristin',
    'Katto',
    'Julkisivu',
    'Räystäs',
    'Ulkoportaat',
  ] },
  { ryhma: 'Yleiset tilat ja kulkureitit', paikat: [
    'Aula',
    'Vastaanotto',
    'Asiakastila',
    'Pääsisäänkäynti',
    'Tuulikaappi',
    'Pyöröovi',
    'Käytävä',
    'Yhdyskäytävä',
    'Siirtymäreitti',
    'Porraskäytävä',
    'Tasanne',
    'Kiinteät tikkaat',
    'Hissi',
    'Hissikuilu',
    'Asiakas-WC',
    'Yleinen saniteettitila',
  ] },
  { ryhma: 'Henkilökunnan tilat ja toimistot', paikat: [
    'Avokonttori',
    'Erillishuone',
    'Työpiste',
    'Neuvotteluhuone',
    'Hiljainen vetäytymistila',
    'Sosiaalitila',
    'Taukohuone',
    'Keittiö',
    'Pukuhuone',
    'Peseytymistila',
    'Takahuone (Back office)',
    'Varustehuone',
  ] },
  { ryhma: 'IT- ja turvallisuustilat', paikat: [
    'Konesali',
    'Palvelinhuone',
    'Ristikytkentätila',
    'IT-jakamo',
    'Järjestelmäkaappi',
    'Kytkinkaappi',
    'Laiteteline',
    'Arkisto',
    'Asiakirjavarasto',
    'Turvakaappi',
    'Valvomo',
    'Turvallisuuskeskus',
  ] },
  { ryhma: 'Tekniset tilat ja kiinteistöhuolto', paikat: [
    'Sähköpääkeskus',
    'Alakeskus',
    'Muuntamo',
    'Ilmanvaihtokonehuone (IV-konehuone)',
    'Sprinklerikeskus',
    'Palovesipumppaamo',
    'Kellari',
    'Tekninen tunneli',
    'Alapohja',
    'Varavoimakonehuone',
    'UPS-tila',
    'Polttoainesäiliö',
    'Lämmönjakohuone',
    'Kylmäkonehuone',
    'Vesipumppaamo',
    'Jätevesipumppaamo',
    'Lattiakaivo',
  ] },
  { ryhma: 'Tuotanto, logistiikka ja työmaat', paikat: [
    'Tuotantohalli',
    'Kokoonpanolinjasto',
    'Tehdassali',
    'Varasto',
    'Korkeavarasto',
    'Materiaalialue',
    'Kylmävarasto',
    'Pakastamo',
    'Trukkikäytävä',
    'Hyllyväli',
    'Materiaalinkäsittelyalue',
    'Kemikaalivarasto',
    'Palavan nesteen varasto',
    'Työmaa-alue',
    'Tilapäisrakenne',
    'Rakennusteline',
    'Välipohjan aukko',
    'Kaivanto',
  ] },
  { ryhma: 'Ajoneuvot ja työkoneet', paikat: [
    'Vartijan partioauto',
    'Yrityksen henkilöauto',
    'Trukki',
    'Pumppukärry',
    'Vihivaunu (AGV)',
    'Pyöräkuormaaja',
    'Kaivinkone',
    'Kuorma-auto',
    'Perävaunu',
  ] },
];

export const AIHEET: { aihe: string; alueet: { alue: string; rivit: [Luokka, string][] }[] }[] = [
  { aihe: 'Tieto- ja kyberturvallisuus', alueet: [
    { alue: 'Työpisteet (Clean Desk & Screen)', rivit: [
      ['havainto', 'Työpiste tarkastettu (Clean Desk -ohjeistuksen mukainen)'],
      ['havainto', 'Työpiste tarkastettu (puutteita havaittu)'],
      ['poikkeama', 'Työaseman näyttö jätetty lukitsematta (Clean Screen -puute)'],
      ['poikkeama', 'Salasana havaittu kirjoitettuna (esim. Post-it -lappu näytössä)'],
      ['poikkeama', 'Luottamukselliseksi luokiteltu asiakirja jätetty työpöydälle'],
      ['toimenpide', 'Arkaluonteinen asiakirja siirretty lukittuun tilaan / roskakoriin'],
      ['havainto', 'Kannettava tietokone jätetty kiinnittämättä vaijerilukolla'],
      ['poikkeama', 'Luvaton ulkoinen tallennusmedia (USB-muisti, ulkoinen kovalevy) työpöydällä'],
      ['poikkeama', 'Työntekijän avaimet tai kulkutunniste jätetty työpöydälle valvomatta'],
      ['havainto', 'Älypuhelin tai tabletti jätetty valvomatta työpisteelle'],
      ['poikkeama', 'Valkotaululla / fläppitaululla luottamuksellista tietoa avoimessa tilassa'],
      ['havainto', 'Tietosuojasermi (Privacy Screen) puuttuu tai on käännetty sivuun'],
    ] },
    { alue: 'Tulostimet ja asiakirjahallinta', rivit: [
      ['poikkeama', 'Tulosteita jätetty monitoimilaitteelle valvomatta'],
      ['poikkeama', 'Luottamuksellisia tulosteita löytynyt tulostimelta'],
      ['toimenpide', 'Hylättyjen tulosteiden vieminen tietoturva-astiaan (silppuaminen)'],
      ['havainto', 'Tietoturvaroska-astian lukitus puutteellinen tai astia ylitäynnä'],
      ['poikkeama', 'Tavalliseen roskakoriin heitetty yrityksen sisäistä materiaalia'],
      ['toimenpide', 'Neuvotteluhuoneen valkotaulu pyyhitty vartijan toimesta'],
      ['toimenpide', 'Neuvotteluhuoneeseen unohdetut asiakirjat toimitettu löytötavaroihin'],
      ['poikkeama', 'Arkistohuoneen ovi jätetty auki tai lukitsematta'],
    ] },
    { alue: 'Konesalit ja IT-laitetilat (Equipment Siting)', rivit: [
      ['poikkeama', 'Konesalin ovi jätetty raolleen / pönkitetty auki'],
      ['toimenpide', 'Konesalin oven lukituksen fyysinen testaus (kunnossa)'],
      ['poikkeama', 'Palvelinkaapin lukitus puutteellinen tai ovi auki'],
      ['havainto', 'Kytkinkaapin (ristikytkentä) ovi raollaan kerrostilassa'],
      ['havainto', 'Kaapelointi irti, epäsiisti tai vaurioitunut'],
      ['poikkeama', 'Tuntematon laite (esim. reititin, Raspberry Pi) kytketty verkkoon'],
      ['toimenpide', 'Konesalin lämpötilavaroituksen tai kosteushälytyksen visuaalinen kuittaus'],
      ['poikkeama', 'IT-laitteiston siirto valvomatta käytävillä tai lastauslaiturilla'],
      ['havainto', 'Palvelinhuoneen ilmastointilaitteen epänormaali ääni tai vuoto'],
      ['poikkeama', 'Konesalin kameravalvonnan peittoalueella esteitä'],
    ] },
    { alue: 'Kulkutunnisteet, vieraat ja sosiaalinen manipulointi', rivit: [
      ['havainto', 'Työntekijän henkilökortti ei ole näkyvillä ohjeistuksen mukaisesti'],
      ['poikkeama', 'Tunnistamaton henkilö IT-tiloissa ilman saattajaa'],
      ['poikkeama', 'Tailgating / peesaus -yritys havaittu kulkuportilla tai ovella'],
      ['toimenpide', 'Vierailijan saattaminen vastaanottoon (saattamaton vieras tavattu)'],
      ['poikkeama', 'Luvaton valokuvaaminen tai videointi toimitiloissa'],
      ['toimenpide', 'Tietoturvaohjeistuksen antaminen tai kertaaminen vierailijalle'],
      ['poikkeama', 'Vierailijakortin palauttamatta jättäminen (vieras poistunut)'],
      ['poikkeama', 'Sosiaalisen manipuloinnin yritys (esim. tekeytyminen huoltomieheksi)'],
      ['toimenpide', 'Kadonneesta kulkutunnisteesta ilmoituksen vastaanottaminen'],
      ['poikkeama', 'Ulkopuolinen urakoitsija ilman vaadittavaa IT-valvojaa kriittisessä tilassa'],
    ] },
  ] },
  { aihe: 'Kiinteistö- ja toimitilaturvallisuus', alueet: [
    { alue: 'Ovet, lukitukset ja kulkureitit', rivit: [
      ['toimenpide', 'Ovi avattu (rutiini / aamukierros / tilan käyttöönotto)'],
      ['toimenpide', 'Ovi lukittu (rutiini / iltakierros / tilan sulkeminen)'],
      ['toimenpide', 'Ovi pönkitetty luvattomasti auki (kiila tai este poistettu)'],
      ['havainto', 'Ovi ei mene lukkoon (salpautumisvika, mekaaninen este)'],
      ['poikkeama', 'Lukon telki, vastarauta tai sylinteri vaurioitunut tai jumissa'],
      ['havainto', 'Ovikoneisto pitää epänormaalia ääntä tai toimii viiveellä'],
      ['havainto', 'Saranan säätö tai voitelun tarve havaittu (ovi roikkuu tai ottaa karmiin)'],
      ['poikkeama', 'Kulkutunnistelukija pimeänä, irti seinästä tai epäkunnossa'],
      ['havainto', 'Tavaravastaanoton nosto-ovi jätetty auki ilman valvontaa'],
      ['toimenpide', 'Fyysisten avainten luovutus (kuittaus järjestelmään)'],
      ['toimenpide', 'Fyysisten avainten palautuksen vastaanotto ja kaappiin sijoitus'],
      ['poikkeama', 'Avainsäilön (esim. putkilukko) kansi auki tai vaurioitunut'],
      ['poikkeama', 'Sähkölukon vikatila (lukko jäänyt auki-asentoon jännitteen katketessa)'],
      ['poikkeama', 'Magneettikoskettimen (rikosilmoitinjärjestelmä) vaurio tai peukalointi'],
    ] },
    { alue: 'Ikkunat, lasirakenteet ja julkisivu', rivit: [
      ['toimenpide', 'Ikkuna jätetty auki työajan ulkopuolella (suljettu vartijan toimesta)'],
      ['havainto', 'Ikkunan lukitusmekanismi tai painike rikki'],
      ['poikkeama', 'Lasirikko, särö tai naarmu ikkunassa / lasiovessa'],
      ['havainto', 'Ikkunan turva- tai auringonsuojakalvo vaurioitunut / kuoriutuu'],
      ['toimenpide', 'Sälekaihtimet tai rullaverhot laskettu turvallisuussyistä (näkyvyyden esto)'],
      ['poikkeama', 'Julkisivun verhouslevy irti tai roikkuu vaarallisesti'],
      ['havainto', 'Katon vesikouru tai syöksytorvi irti / tukossa (visuaalinen havainto)'],
    ] },
    { alue: 'Alue- ja kehäsuojaus (Perimeter Security)', rivit: [
      ['poikkeama', 'Alueaita rikki, leikattu auki tai kaatunut'],
      ['poikkeama', 'Ajoportti tai henkilöportti jätetty luvattomasti auki'],
      ['havainto', 'Portin automatiikka ei reagoi, jäänyt jumiin tai turvareuna vaurioitunut'],
      ['havainto', 'Tuntematon ajoneuvo piha-alueella aukioloaikojen ulkopuolella'],
      ['poikkeama', 'Luvaton pysäköinti pelastustiellä (siirtokehotus tai ilmoitus)'],
      ['havainto', 'Luvaton pysäköinti invapaikalla tai varatulla paikalla'],
      ['havainto', 'Roskia, hylättyjä tavaroita tai romua kiinteistön seinustalla'],
      ['toimenpide', 'Kiipeämisen mahdollistava esine (esim. kuormalava, tikkaat) aidan vieressä'],
      ['havainto', 'Kiipeämisen estävien rakenteiden (esim. piikkilanka/yläosa) vauriot'],
      ['havainto', 'Kasvillisuus peittää näkyvyyttä tai yltää aitaan kiinni (raivaustarve)'],
    ] },
    { alue: 'Valaistus ja tekninen valvonta (CCTV)', rivit: [
      ['havainto', 'Ulkovalaistus pimeänä kokonaan tai osittain (alue/reitti)'],
      ['havainto', 'Sisävalaistus pimeänä / palanut loisteputki tai polttimo'],
      ['toimenpide', 'Palanut lamppu vaihdettu (jos kuuluu vartijan tehtäviin)'],
      ['havainto', 'Liiketunnistin ei reagoi tai reagoi viiveellä'],
      ['havainto', 'Valaistuksen hämäräkytkin tai ajastin väärässä ajassa'],
      ['toimenpide', 'Kameran linssi likainen / hämähäkinverkko poistettu linssin edestä'],
      ['poikkeama', 'Kameran suuntaus pielessä, käännetty tahallaan tai peitetty'],
      ['havainto', 'Kameran IR-valo (pimeänäkö) ei toimi'],
      ['havainto', 'Kameran kiinnitysjalka löysällä'],
      ['havainto', 'Kameran kotelossa kosteutta sisällä'],
    ] },
    { alue: 'Talotekniikka ja sisärakenteet', rivit: [
      ['havainto', 'Kattolevy (alakatto) irti, roikkuu tai puuttuu'],
      ['havainto', 'Seinässä, lattiassa tai pilarissa mekaaninen törmäysvaurio'],
      ['havainto', 'Lattiamateriaali repsottaa, kynnyslista irti tai matto rullalla'],
      ['poikkeama', 'Ilmastointiventtiili teipattu umpeen luvattomasti (työntekijän toimesta)'],
      ['havainto', 'Epätavallinen ääni, tärinä tai haju ilmanvaihtokonehuoneesta'],
      ['toimenpide', 'Hissin vikanapin tai hätäpuhelimen testaus suoritettu'],
      ['poikkeama', 'Hissi jumissa, ovet eivät sulkeudu tai hissi pitää outoa ääntä'],
      ['havainto', 'Lämpöpatterin termostaatti irronnut, vuotaa tai on säädetty ääriasentoon'],
      ['poikkeama', 'Kaiteen tai käsijohteen heiluminen (kiinnitys pettänyt)'],
      ['poikkeama', 'Lattialuukku tai huoltoluukku jätetty auki ja merkitsemättä'],
    ] },
  ] },
  { aihe: 'Varautuminen ja kriisinhallinta', alueet: [
    { alue: 'Ensiapu- ja hätävarusteet', rivit: [
      ['havainto', 'Ensiapulaukun sinetti tarkastettu ja ehjä (valmius kunnossa)'],
      ['toimenpide', 'Ensiapulaukun sisältö vajaa, sinetti murrettu (täydennystilaus tehty)'],
      ['havainto', 'Defibrillaattorin (sydäniskurin) merkkivalo vihreä (visuaalinen tarkastus)'],
      ['poikkeama', 'Defibrillaattorin akku varoittaa vähäisestä varauksesta tai elektrodit vanhentuneet'],
      ['poikkeama', 'Defibrillaattorin kaappi avattu (hälytys aktivoitunut)'],
      ['havainto', 'Silmänhuuhtelupullon nesteen vanhenemispäivän tarkastus'],
      ['toimenpide', 'Hätäsuihkun koekäyttö (veden juoksutus ja kirjaus)'],
      ['toimenpide', 'Evakuointirepun / kriisilaatikon sisällön pistokoe tai sinetin tarkastus'],
      ['havainto', 'Evakuointituolin (esim. porraskiipijä) sijoituspaikka ja kunto tarkastettu'],
      ['havainto', 'Varavesikanisterien tai hätämuonapakkauksien tarkastus'],
    ] },
    { alue: 'Varajärjestelmät ja viestintä', rivit: [
      ['havainto', 'Varavirtageneraattorin (UPS) silmämääräinen tarkastus (ei vikavaloja)'],
      ['poikkeama', 'UPS-laitteen vikavalo palaa tai laite piippaa'],
      ['havainto', 'Varavoimakoneen polttoainetaso ja öljynpaine tarkastettu visuaalisesti'],
      ['toimenpide', 'Varavoimakoneen koekäytön valvonta / automaattisen testin kuittaus'],
      ['poikkeama', 'Varakäyntijärjestelmän (esim. hätävalojen) akku vuotaa tai kuumentunut'],
      ['havainto', 'Taskulamppujen ja hätävalaisimien toiminnan testaus'],
      ['toimenpide', 'Taskulampun paristojen tai ladattavien akkujen vaihto'],
      ['toimenpide', 'Hätäpuhelimen (esim. GSM/satelliitti) koesoitto suoritettu'],
      ['havainto', 'Radiopuhelinten (TETRA/VHF) lataustilan ja kuuluvuuden tarkastus'],
      ['toimenpide', 'Megafonin paristojen testaus ja sijoituspaikan tarkastus'],
    ] },
    { alue: 'Dokumentaatio, ohjeistukset ja opasteet', rivit: [
      ['havainto', 'Pelastussuunnitelma-kansion fyysinen sijainti ja saatavuus tarkastettu'],
      ['havainto', 'Hätänumerolista tai toimintaohjetaulu ajan tasalla (seinällä kiinni)'],
      ['havainto', 'Kokoontumispaikan opastekyltti puuttuu, vaurioitunut tai huonosti näkyvissä'],
      ['havainto', 'Kriisiviestintäkansion tai poikkeustilan johtokeskuksen laatikon sinetti ehjä'],
      ['havainto', 'Vaara-aluekylttien ja varoitustaulujen luettavuus varmistettu'],
      ['havainto', 'Päivystyslistan (henkilöiden yhteystiedot) päivitystarve huomattu'],
    ] },
    { alue: 'Tilannekuva ja sääilmiöihin varautuminen', rivit: [
      ['toimenpide', 'Irtotavaroiden (esim. pihakalusteet, roskikset) siirto tai sitominen turvaan (myrskyvaroitus)'],
      ['toimenpide', 'Sadevesikaivojen ja viemärien ritilöiden puhdistus roskista / lehdistä (tulvavaroitus)'],
      ['havainto', 'Lumikuorman ja jäämuodostumien tarkkailu (katto, katokset, rakenteet)'],
      ['toimenpide', 'Vaarallisten jääpuikkojen pudottaminen tai alueen eristäminen kulkureitin yltä'],
      ['poikkeama', 'Poikkeava, toistuva tai pitkittynyt sähkökatko rekisteröity kiinteistössä'],
      ['havainto', 'Vedenpinnan nousun havainnointi kellaritiloissa, hissikuiluissa tai pysäköintihalleissa'],
      ['toimenpide', 'Myrskyvaurioiden (esim. kaatuneet puut, irronneet pellit) kartoittaminen'],
    ] },
  ] },
  { aihe: 'Väärinkäytösten ja poikkeamien hallinta', alueet: [
    { alue: 'Epäilyttävä toiminta ja tiedustelu', rivit: [
      ['poikkeama', 'Tuntematon henkilö kuvaa, kiikaroi tai piirtää havaintoja kiinteistöstä'],
      ['poikkeama', 'Epäilyttävä, hylätty laukku tai paketti havaittu (tilannearvio tehty)'],
      ['toimenpide', 'Luvaton oleskelu alueella (henkilö puhutettu ja poistettu alueelta)'],
      ['havainto', 'Luvaton oleskelu alueella (henkilö poistui itse huomattuaan vartijan)'],
      ['poikkeama', 'Tavaroiden, ovien tai lukkojen asiaton kokeilu / penkominen'],
      ['poikkeama', 'Dronen / miehittämättömän ilma-aluksen lennätys kiinteistön yllä'],
      ['toimenpide', 'Myymäläetsivän, poliisin tai henkilökunnan avustaminen kiinniottotilanteessa'],
      ['havainto', 'Epäilyttävä ajoneuvo (esim. pakettiauto) kiertää aluetta toistuvasti'],
      ['poikkeama', 'Tuntemattoman henkilön tekemät poikkeavat kyselyt henkilökunnasta tai rutiineista'],
      ['poikkeama', 'Postin tai roskalaatikoiden penkominen (identiteettivarkauden/tiedonkeruun riski)'],
    ] },
    { alue: 'Ilkivalta, vahingonteot ja sabotaasi', rivit: [
      ['havainto', 'Töherrys, tägi tai graffiti havaittu seinässä / opasteissa'],
      ['toimenpide', 'Töherryksen välitön puhdistus tai poisto (jos mahdollista)'],
      ['toimenpide', 'Luvaton juliste, tarra tai mainos poistettu kiinteistön alueelta'],
      ['poikkeama', 'Paikkojen rikkominen (esim. bussikatos, roskakori, istutukset revitty)'],
      ['poikkeama', 'Lukon tai kortinlukijan tahallinen tukkiminen (esim. liimalla, tikulla, purukumilla)'],
      ['poikkeama', 'Valvontakameran tahallinen kääntäminen, peittäminen, maalaaminen tai rikkominen'],
      ['poikkeama', 'Palohälyttimen tai sprinklerisuuttimen ilkivaltainen laukaisu / rikkominen'],
      ['poikkeama', 'Ajoneuvojen naarmuttaminen tai renkaiden puhkominen pysäköintialueella'],
    ] },
    { alue: 'Käytöshäiriöt ja väkivallan uhka', rivit: [
      ['toimenpide', 'Häiriköivä tai meluava henkilö poistettu tiloista'],
      ['toimenpide', 'Aggressiivinen asiakas tai vierailija (tilanne rauhoitettu puhuttamalla)'],
      ['toimenpide', 'Päihtynyt tai sekavasti käyttäytyvä henkilö ohjattu ulos'],
      ['poikkeama', 'Sanallinen uhkaus tai kiroilu henkilökuntaa, asiakkaita tai vartijaa kohtaan'],
      ['toimenpide', 'Nuorisojoukon tai jengin siirtäminen pois sisäänkäynniltä / kauppakeskuksesta'],
      ['poikkeama', 'Tappelu tai fyysinen konflikti (väliintulo tai poliisin kutsuminen)'],
      ['poikkeama', 'Häiriköinti wc-tiloissa (esim. lukittautuminen, ilkivalta)'],
    ] },
    { alue: 'Sisäiset sääntörikkomukset ja laiminlyönnit', rivit: [
      ['toimenpide', 'Luvaton tupakointi alueella tai sisätiloissa (henkilöä huomautettu)'],
      ['poikkeama', 'Alkoholin tai huumausaineiden luvaton käyttö / hallussapito alueella'],
      ['poikkeama', 'Luvaton yöpyminen kiinteistössä, varastossa tai teknisissä tiloissa'],
      ['havainto', 'Omien laitteiden (esim. sähköpotkulauta, lämmitin) luvaton lataus (sähkövarkaus/paloriski)'],
      ['havainto', 'Roskien tahallinen heittäminen maahan (roskaaminen)'],
      ['poikkeama', 'Jätelavalle tai kierrätyspisteelle luvaton tunkeutuminen (dyykkaus)'],
      ['poikkeama', 'Yrityksen omaisuuden luvaton siirtäminen tai anastamisen yritys'],
      ['havainto', 'Turvavaatetuksen tai ID-kortin tahallinen käyttämättä jättäminen (toistuva)'],
    ] },
  ] },
  { aihe: 'Pelastusturvallisuus', alueet: [
    { alue: 'Sammutuskalusto ja laitteistot', rivit: [
      ['havainto', 'Alkusammuttimen silmämääräinen tarkastus (mittari vihreällä, leima voimassa)'],
      ['poikkeama', 'Alkusammutin puuttuu paikaltaan tai on siirretty lattialle'],
      ['havainto', 'Alkusammuttimen tarkastusleima on vanhentunut'],
      ['poikkeama', 'Alkusammuttimen sokka puuttuu tai sinetti on murrettu'],
      ['toimenpide', 'Alkusammutin nostettu / siirretty takaisin viralliselle paikalleen'],
      ['havainto', 'Sammutuspeitteen tarkastus (kotelo ehjä, nauhat esillä)'],
      ['havainto', 'Pikapalopostin luukku tukittu tavaralla, teipattu kiinni tai lukossa'],
      ['poikkeama', 'Pikapalopostin letku rullattu väärin, suutin puuttuu tai letku irti'],
      ['toimenpide', 'Pikapalopostin koekäyttö / veden juoksutus suoritettu'],
    ] },
    { alue: 'Palonilmaisu ja automaattiset järjestelmät', rivit: [
      ['toimenpide', 'Palovaroittimen pariston vaihto (itsenäiset varoittimet)'],
      ['poikkeama', 'Palovaroitin puuttuu, on irrotettu katosta tai huputettu luvattomasti'],
      ['toimenpide', 'Paloilmoitinkeskuksen (FAP) vikailmoituksen luku ja kuittaus'],
      ['poikkeama', 'Paloilmoittimen manuaalipainikkeen lasi rikki tai painettu sisään'],
      ['poikkeama', 'Sprinklerisuuttimen edessä tai lähellä este (vaatimus min. 50 cm vapaata tilaa)'],
      ['havainto', 'Sprinklerikeskuksen venttiilien visuaalinen tarkastus (lukittu oikeaan asentoon)'],
      ['havainto', 'Savunpoistoluukkujen painikkeiden ja keskuksen tilan tarkastus'],
      ['havainto', 'Ilmastoinnin hätäseis-painikkeen esteettömyys varmistettu'],
    ] },
    { alue: 'Poistumistiet, opasteet ja palo-osastointi', rivit: [
      ['poikkeama', 'Poistumistie tai hätäuloskäynti tukittu (tavaraa, roskia tai lavoja reitillä)'],
      ['toimenpide', 'Tavarat siirretty pois poistumistieltä esteettömän kulun varmistamiseksi'],
      ['poikkeama', 'Hätäpoistumistien ovi on jumissa, jäätynyt tai ei aukea työntämällä'],
      ['poikkeama', 'Hätäpoistumistien oven lukitus ei avaudu (esim. avauspainike viallinen)'],
      ['havainto', 'Poistumistien valaistu opaste (vihreä ukkeli) pimeänä (akku/lamppu rikki)'],
      ['havainto', 'Jälkivalaiseva poistumisopaste likainen, peitetty tai irronnut'],
      ['poikkeama', 'Palo-oven luvaton kiilaus auki (esim. roskakorilla tai puukiilalla)'],
      ['toimenpide', 'Palo-oven kiila poistettu ja ovi suljettu vartijan toimesta'],
      ['havainto', 'Palo-oven sulkijamekanismi ei toimi (ovi ei mene itsestään kiinni/salpaan)'],
      ['poikkeama', 'Palo-osastoinnin rakenteellinen vaurio (esim. reikä seinässä, palomassa puuttuu)'],
    ] },
    { alue: 'Palokuorma, kuumatyöt ja muut riskit', rivit: [
      ['poikkeama', 'Palokuormaa (esim. pahvia, roskia) varastoitu sähköpääkeskukseen'],
      ['toimenpide', 'Palokuorma poistettu sähköpääkeskuksesta välittömästi'],
      ['poikkeama', 'Tulenarkojen aineiden (kaasut, nesteet) virheellinen säilytys avotilassa'],
      ['toimenpide', 'Kuumatyöluvan voimassaolon, rajauksen ja sammuttimien tarkastus'],
      ['toimenpide', 'Kuumatyöpaikan jälkivartioinnin suorittaminen (esim. 1h työn päättymisestä)'],
      ['poikkeama', 'Luvaton tulenteko, avotuli tai grillin käyttö kiinteistön alueella'],
      ['toimenpide', 'Tuhkakuppi tai roskis savuaa (sammutettu tai tyhjennetty paloturvallisesti)'],
      ['havainto', 'Siirrettävä sähkölämmitin jätetty päälle valvomatta tai liian lähelle palavaa materiaalia'],
      ['toimenpide', 'Sähkölämmitin sammutettu ja paloriski poistettu'],
    ] },
  ] },
  { aihe: 'Henkilöstöturvallisuus', alueet: [
    { alue: 'Opastus, avustaminen ja läsnäolo', rivit: [
      ['toimenpide', 'Asiakkaan tai vierailijan opastus (reitin neuvominen, tilojen osoittaminen)'],
      ['toimenpide', 'Henkilökunnan proaktiivinen opastus turvallisuusasiassa tai säännöissä'],
      ['toimenpide', 'Eksyneen henkilön auttaminen ja saattaminen oikeaan kohteeseen'],
      ['toimenpide', 'Työntekijän saattaminen autolle/pysäkille (turvallisuussyistä, pimeällä)'],
      ['toimenpide', 'Tavaran, ovien tai raskaiden kantamusten kanssa avustaminen'],
      ['toimenpide', 'Kieli- tai kommunikaatio-ongelmatilanteen selvittäminen ja ratkaisu'],
      ['toimenpide', 'Löytötavaran vastaanotto, kirjaus ja turvallinen säilytys'],
      ['toimenpide', 'Taksien tai muun kuljetuksen tilaamisessa avustaminen'],
    ] },
    { alue: 'Ensiapu, sairastumiset ja tapaturmat', rivit: [
      ['toimenpide', 'Ensiaputilanne (pieni, esim. laastarin, särkylääkkeen tai siteen anto)'],
      ['poikkeama', 'Sairaskohtaus (hätäkeskukseen soitto, ambulanssi tilattu)'],
      ['toimenpide', 'Henkilö kaatunut (avustettu ylös, ei vakavaa vammaa, tilanne tarkistettu)'],
      ['toimenpide', 'Kylmäpussin luovutus ja käyttöopastus lievään ruhjeeseen'],
      ['toimenpide', 'Silmänhuuhtelupisteen käytön opastus ja avustaminen huuhtelussa'],
      ['toimenpide', 'Psyykkisen ensiavun antaminen (esim. shokissa olevan rauhoittelu)'],
    ] },
    { alue: 'Kulkuluvat, tunnistautuminen ja käyttöoikeudet', rivit: [
      ['toimenpide', 'Henkilökortin tai kuvallisen henkilöllisyystodistuksen tarkastus'],
      ['toimenpide', 'Työntekijän kulkuoikeuksien, PIN-koodien tai järjestelmien käytön opastus'],
      ['toimenpide', 'Tilapäisen kulkukortin luovutus, kirjaus ja palautuksen valvonta'],
      ['toimenpide', 'Kadonneen tai varastetun henkilökortin kuoletus ja ilmoituksen teko'],
      ['havainto', 'Henkilökortti lainattu kollegalle luvattomasti (huomautettu ja raportoitu)'],
      ['toimenpide', 'Työntekijä unohtanut koodin/avaimen (henkilöllisyys todennettu ja ovi avattu)'],
    ] },
    { alue: 'Hyvinvointi, yksintyöskentely ja psykososiaalinen kuormitus', rivit: [
      ['toimenpide', 'Yksintyöskentelevän henkilön tarkastussoitto suoritettu sovitusti'],
      ['toimenpide', 'Yksintyöskentelevän työntekijän fyysinen tarkastuskäynti paikan päällä'],
      ['havainto', 'Havainto silminnähden ylirasittuneesta, sairaasta tai poissaolevasta työntekijästä'],
      ['toimenpide', 'Uhkaavan puhelun vastaanottaneen työntekijän rauhoittaminen ja tukeminen'],
      ['havainto', 'Ergonomiahavainto (esim. väärä työasento, tuolin säätötarve suositeltu)'],
      ['toimenpide', 'Työpaikkakiusaamiseen, ahdisteluun tai epäasialliseen käytökseen puuttuminen'],
      ['toimenpide', 'Kuulovamman, näkövamman tai liikuntarajoitteen huomioiva erityisavustus'],
    ] },
  ] },
  { aihe: 'Ympäristöturvallisuus', alueet: [
    { alue: 'Vuodot, päästöt ja vahingot', rivit: [
      ['toimenpide', 'Kemikaalivuoto (pieni, rajattu ja puhdistettu imeytysaineella)'],
      ['poikkeama', 'Kemikaalivuoto (suuri tai tuntematon aine, ilmoitettu pelastuslaitokselle)'],
      ['havainto', 'Öljytahra, polttoainevuoto tai hydrauliikkaneste lattiassa tai asfaltissa'],
      ['toimenpide', 'Öljytahra imeytetty, siivottu ja jäte toimitettu ongelmajätteeseen'],
      ['havainto', 'Vuotava vesihana, WC-istuin tai suihku havaittu (ilmoitus huoltoon)'],
      ['poikkeama', 'WC:n tai pesualtaan vesivahingon alku (pönttö tulvii yli reunojen)'],
      ['poikkeama', 'Vuotava putki, lämpöpatteri tai ilmastointilaitteen kondenssivesi'],
      ['havainto', 'Lattiakaivo vetää huonosti, pulppuaa tai on täysin tukossa'],
      ['toimenpide', 'Lattiakaivon puhdistus hiuksista tai roskista (pieni hätätoimenpide)'],
      ['poikkeama', 'Jätevesipumppaamon hälytysvalon palaminen'],
    ] },
    { alue: 'Jätehuolto, kierrätys ja ongelmajätteet', rivit: [
      ['havainto', 'Jäteastian, lavan tai puristimen ylitäyttö (pursuaa yli, ei mene kiinni)'],
      ['havainto', 'Jätepuristin tai pahviprässi jumissa / vikatilassa'],
      ['poikkeama', 'Ongelmajäte (esim. akku, loisteputki, maalit) laitettu sekajätteeseen'],
      ['havainto', 'Jätteiden ilmeinen lajitteluvirhe (esim. metallia pahvikeräyksessä)'],
      ['toimenpide', 'Roskien ja irtotavaroiden keruu/siivous kiinteistön ulkoalueelta'],
      ['toimenpide', 'Jätekatoksen ovi tai lukitus jätetty auki (suljettu vartijan toimesta)'],
      ['poikkeama', 'Biovaarallisen jätteen (esim. neulat, veriset siteet) väärä sijoittelu'],
      ['havainto', 'Asiakirjatuhoojan (silppuri) säiliö täynnä ja jumissa'],
    ] },
    { alue: 'Energia, resurssitehokkuus ja LVI', rivit: [
      ['toimenpide', 'Turha valaistus sammutettu tyhjistä neuvotteluhuoneista tai käytäviltä'],
      ['toimenpide', 'Ikkuna suljettu lämpöhukan tai jäätymisvaaran estämiseksi'],
      ['havainto', 'Ulko-ovi tai nosto-ovi pidetty tarpeettoman pitkään auki (kylmä/kuuma ilma)'],
      ['havainto', 'Ilmastoinnin oudon kova puhallus, vedon tunne tai epänormaali alipaine'],
      ['havainto', 'Lämpötilan poikkeama (liian kuuma tai kylmä tila suhteessa normaaliin)'],
      ['havainto', 'Aurinkopaneelien tai lämpöpumppujen ulkoyksiköiden silmämääräinen vaurio'],
      ['toimenpide', 'Auton tyhjäkäynti kieltoalueella (kuljettajaa huomautettu)'],
    ] },
    { alue: 'Ympäristön laatu, haitat ja hygienia', rivit: [
      ['havainto', 'Paha tai poikkeava haju (esim. viemärikaasu, otsonin haju, liuottimet)'],
      ['havainto', 'Epänormaali melu, vinkuna tai tärinä kiinteistössä'],
      ['havainto', 'Pölyhaitta havaittu (esim. rakennustyöstä leviävä kivipöly puhdastiloihin)'],
      ['poikkeama', 'Tuhoeläinhavainto (hiiri, rotta, torakat, sokeritoukat) sisätiloissa'],
      ['toimenpide', 'Tuhoeläinloukun tai myrkkysyöttiaseman tarkastus / siirtyminen'],
      ['havainto', 'Lintujen pesintä sisäänkäynnin yllä, varastossa tai lastauslaiturilla (sotkuhaitta)'],
      ['poikkeama', 'Homeen tai kosteusvaurion haju ja visuaalinen havainto rakenteissa'],
    ] },
  ] },
  { aihe: 'Työturvallisuus', alueet: [
    { alue: 'Henkilösuojaimet (PPE - Personal Protective Equipment)', rivit: [
      ['havainto', 'Suojalasit käytössä ohjeen mukaan (positiivinen BBS-havainto)'],
      ['toimenpide', 'Suojalasit tai visiiri puuttuvat vaara-alueella (henkilöä huomautettu)'],
      ['poikkeama', 'Turvakengät puuttuvat tai henkilöllä on sandaalit tuotantotilassa'],
      ['poikkeama', 'Suojakypärä puuttuu, on väärin päin tai leukahihna auki'],
      ['poikkeama', 'Huomiovaatetus (heijastinliivi, varoitusvaate) puuttuu logistiikka-alueella'],
      ['poikkeama', 'Kuulosuojaimet puuttuvat tai on nostettu ylös melualueella'],
      ['poikkeama', 'Putoamissuojaimet tai valjaat puuttuvat korkean paikan työssä (yli 2m)'],
      ['havainto', 'Suojakäsineet vääränlaiset (esim. asennushanska kemikaalityössä)'],
      ['poikkeama', 'Hengityssuojain (esim. FFP2/FFP3, kaasunaamari) puuttuu pölyisessä työssä'],
    ] },
    { alue: 'Liukastumiset, kompastumiset, putoamiset (Slips, Trips, Falls)', rivit: [
      ['toimenpide', 'Korjattu rullalla oleva matonreuna (teipattu tai suoristettu)'],
      ['toimenpide', 'Liukas lattia havaittu ja varoituskyltti "Varo liukasta lattiaa" viety paikalle'],
      ['toimenpide', 'Lattialle läikkynyt neste (vesi, kahvi, pesuaine) kuivattu'],
      ['toimenpide', 'Jäätynyt tai luminen kulkutie hiekoitettu / suolattu vartijan toimesta'],
      ['toimenpide', 'Sähköjohto tai kaapeli kulkuväylällä (siirretty turvaan tai teipattu lattiaan)'],
      ['havainto', 'Epätasainen pihakivetys, kuoppa tai kynnys havaittu (kompastumisvaara)'],
      ['poikkeama', 'Suojakaide, käsijohde tai reunasuojaus puuttuu, irronnut tai on hutera'],
      ['havainto', 'Rappusten liukuesteteippi irronnut tai kulunut pois'],
    ] },
    { alue: 'Siisteys, järjestys ja 5S-menetelmä', rivit: [
      ['havainto', 'Työpiste tai alue pidetty poikkeuksellisen siistinä ja järjestyksessä'],
      ['toimenpide', 'Epäjärjestys korjattu (esim. roskat roskiin, työkalut takaisin paikoilleen)'],
      ['havainto', 'Työkalut, osat tai johdot jätetty lojumaan kulkuväylälle'],
      ['poikkeama', 'Tyhjä kuormalava jätetty pystyyn seinää vasten (kaatumis- ja loukkaantumisvaara)'],
      ['toimenpide', 'Kuormalava käännetty turvallisesti lappeelleen lattialle'],
      ['havainto', 'Pakkausmateriaaleja (esim. muovikelmua) kulkuväylällä'],
    ] },
    { alue: 'Koneet, laitteet, työskentelytavat ja liikenne', rivit: [
      ['havainto', 'Turvallinen nostotekniikka havaittu raskaiden taakkojen käsittelyssä'],
      ['havainto', 'Ergonomisesti huono, selkää kuormittava nosto havaittu'],
      ['toimenpide', 'Rikkinäinen tikapuu, pukki tai jakkara havaittu (lappu kiinni, poistettu käytöstä)'],
      ['poikkeama', 'Trukin tai ajoneuvon ylinopeus alueella / varastossa'],
      ['poikkeama', 'Telineen, siirtolavan tai nostimen pyörien puutteellinen lukitus työn aikana'],
      ['havainto', 'Työkoneen (esim. trukki, kaivinkone) avain jätetty luvatta virtalukkoon'],
      ['poikkeama', 'Koneen mekaanisen suojuksen tai valoverhon ohittaminen (esim. teipattu turvaraja)'],
      ['havainto', 'Trukilla ajo jalankulkualueella tai puutteellinen risteyskäyttäytyminen (ei äänimerkkiä)'],
      ['poikkeama', '"Läheltä piti" -tilanne (Near Miss) raportoitu tai havaittu'],
      ['poikkeama', 'LOTO (Lockout/Tagout) -lukituksen puuttuminen huollettavasta koneesta'],
    ] },
  ] },
  { aihe: 'Tuotannon ja toiminnan turvallisuus', alueet: [
    { alue: 'Logistiikka, varastointi ja materiaalinkäsittely', rivit: [
      ['havainto', 'Kuormalava tai pino huonosti rakennettu (sortumisvaara varastohyllyssä)'],
      ['poikkeama', 'Trukkikäytävä, hyllyväli tai ajoreitti tukittu tavaralla (hidastaa logistiikkaa)'],
      ['toimenpide', 'Tavara siirretty pois trukkikäytävältä turvallisen kulun varmistamiseksi'],
      ['poikkeama', 'Tavaranvastaanoton oven luvaton aukipito (vaikuttaa tuotantotilan olosuhteisiin)'],
      ['havainto', 'Kuormanvarmistus tai sidonta puutteellinen saapuvassa tai lähtevässä rekassa'],
      ['poikkeama', 'Hyllyrakenteen vaurio (esim. trukki törmännyt pystytukeen, vaatii tarkastusta)'],
      ['havainto', 'Varaston enimmäiskorkeuden ylitys (tavara liian lähellä kattoa tai sprinkleriä)'],
      ['havainto', 'Lastauslaiturin turvareuna, tiiviste tai puskuri vaurioitunut'],
      ['havainto', 'Saapuvan kuljetuksen sinetin tai lukituksen tarkastus (ehjä / murrettu)'],
      ['toimenpide', 'Rekan rekisterikilven tai kuljettajan tunnistetietojen kirjaus portilla'],
    ] },
    { alue: 'Prosessit, laitteisto ja laadunvarmistus', rivit: [
      ['toimenpide', 'Tuotantolinjan tai laitteen hätäseishälytyksen/vikavalon ilmoitus ja kuittaus'],
      ['havainto', 'Koneen epänormaali ääni, kitinä tai tärinä havaittu kierroksella'],
      ['havainto', 'Paineilmaverkoston, kaasuputken tai hydrauliikan vuoto (sähinä) havaittu'],
      ['poikkeama', 'Lämpötilapoikkeama varastossa tai pakastamossa (kylmäketjun vaara)'],
      ['toimenpide', 'Tuotantolaitteen paikallisen hälytysvalon palaminen (ilmoitettu valvomoon)'],
      ['havainto', 'Tuotantojätteen (esim. hylkytavara, metallilastu) väärä tai vaarallinen sijoittelu'],
      ['havainto', 'Tuotantokoneen alle kertynyt neste tai raaka-aine (puhdistustarve)'],
      ['havainto', 'Mittarin tai painemittarin lukeman poikkeama ohjearvosta (jos koulutettu seuraamaan)'],
    ] },
    { alue: 'Alihankkijat, urakoitsijat ja huoltotoiminta', rivit: [
      ['toimenpide', 'Huoltomiehen tai urakoitsijan avustaminen / kohteen turvallinen osoitus'],
      ['toimenpide', 'Aliurakoitsijan kulkulupien, Valttikortin tai työlupien tarkistaminen'],
      ['toimenpide', 'Huolto- tai asennustyön satunnainen turvallisuusvalvonta suoritettu'],
      ['toimenpide', 'Huoltoliikkeen jättämä sotku tai romu siivottu / raportoitu vastuuhenkilölle'],
      ['poikkeama', 'Vaara-alueen (esim. nostotyö, sähkötyö) eristys puutteellinen huollon aikana'],
      ['toimenpide', 'Vaara-alueen eristysnauhan, kartioiden tai aitojen pystyttäminen'],
      ['havainto', 'Urakoitsijan käyttämien työkalujen silmämääräinen kunto (esim. johdot rikki)'],
    ] },
    { alue: 'Toimitusketjun jatkuvuus ja omaisuudensuoja', rivit: [
      ['havainto', 'Tavarantoimitus saapunut poikkeavaan aikaan tai ilmoittamatta'],
      ['toimenpide', 'Lähetyksen pakkauksen vaurio havaittu vastaanotossa (valokuvattu todisteeksi)'],
      ['toimenpide', 'Arvotavaran, elektroniikan tai vaarallisten aineiden varastoinnin lukituksen varmistus'],
      ['havainto', 'Materiaalipula tai raaka-aineen loppuminen havaittu kriittisessä pisteessä'],
      ['toimenpide', 'Lastaamattoman tai purkamattoman perävaunun turvalukituksen asetus (vetotappilukko)'],
      ['toimenpide', 'Avainkomponenttien (esim. palvelimet, muotit) siirron dokumentointi ja valvonta'],
    ] },
  ] },
];
